# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: react-application
#   namespace: app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       run: react-application
#   template:
#     metadata:
#       labels:
#         run: react-application
#     spec:
#       containers:
#       - name: react-application
#         image: nginx:stable-perl
#         # image: docker.io/anaisurlichs/react-example:0.0.3
#         ports:
#           - containerPort: 80
#         imagePullPolicy: Always
#         resources:
#           limits:
#             memory: 512Mi
#             cpu: 200m
#         securityContext:
#           allowPrivilegeEscalation: false

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: sudohardik/sample-flask-app:5
        name: flaskdemo
        resources: {}
status: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lb-service
#   labels:
#     app: lb-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 5000
#   selector:
#     app: flaskdemo
