# apiVersion: v1
# kind: Service
# metadata:
#   name: react-application
#   namespace: app
#   labels:
#     run: react-application
# spec:
#   type: NodePort
#   ports:
#   - port: 8080
#     targetPort: 80
#     protocol: TCP
#     name: http
#   selector:
#     run: react-application

apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
